package org.metadatacenter.artifacts.mcp;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.metadatacenter.artifacts.model.core.TemplateSchemaArtifact;
import org.metadatacenter.artifacts.model.reader.JsonArtifactReader;
import org.metadatacenter.artifacts.model.renderer.YamlArtifactRenderer;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.OffsetDateTime;
import java.util.LinkedHashMap;

/**
 * One-shot regeneration utility for the golden YAML fixtures under
 * {@code src/test/resources/hubmap-golden/}.
 *
 * <p>The HuBMAP YAML files (as shipped) are non-canonical against the current
 * artifact library — they omit required metadata ({@code modelVersion},
 * {@code version}, {@code status}) and contain bare-integer values where the
 * library expects strings. Rather than make the MCP tool lenient toward those
 * deviations, the test battery uses canonical YAML generated by the library
 * itself, by round-tripping the paired authoritative JSON Schema through:
 *
 * <pre>{@code
 *   JsonArtifactReader.readTemplateSchemaArtifact
 *     -> YamlArtifactRenderer.renderTemplateSchemaArtifact
 *     -> SnakeYAML dump
 * }</pre>
 *
 * <p>This produces "what the library considers golden YAML" for each template,
 * which the IT then feeds back through {@code template_from_yaml}.
 *
 * <p>Run via:
 *
 * <pre>{@code
 *   mvn test-compile exec:java \
 *       -Dexec.classpathScope=test \
 *       -Dexec.mainClass=org.metadatacenter.artifacts.mcp.GoldenYamlGenerator \
 *       -Dexec.args="/path/to/HuBMAP/templates src/test/resources/hubmap-golden"
 * }</pre>
 *
 * <p>Not a unit test; ignored by surefire/failsafe because it has no
 * {@code @Test} methods. Lives under {@code src/test/java} so the regeneration
 * source-of-truth is checked in alongside the fixtures it produces.
 */
public final class GoldenYamlGenerator
{
  private GoldenYamlGenerator() {}

  public static void main(String[] args) throws IOException
  {
    if (args.length != 2) {
      System.err.println("usage: GoldenYamlGenerator <input-dir-with-json> <output-dir-for-yaml>");
      System.exit(1);
    }
    Path inDir = Paths.get(args[0]);
    Path outDir = Paths.get(args[1]);
    if (!Files.isDirectory(inDir))
      throw new IllegalArgumentException("input dir does not exist: " + inDir);
    Files.createDirectories(outDir);

    ObjectMapper jackson = new ObjectMapper();
    JsonArtifactReader reader = new JsonArtifactReader();
    // isCompact=false so the renderer emits modelVersion / version / status — the
    // strict YamlArtifactReader requires those. (The library's compact form drops
    // them on render but the reader still requires them on read; that asymmetry is
    // the reason for using the explicit form here.)
    YamlArtifactRenderer renderer = new YamlArtifactRenderer(false);

    DumperOptions opts = new DumperOptions();
    opts.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
    opts.setPrettyFlow(true);
    opts.setIndent(2);
    opts.setSplitLines(false);


    int ok = 0;
    int fail = 0;
    try (DirectoryStream<Path> ds = Files.newDirectoryStream(inDir, "*.json")) {
      for (Path jsonFile : ds) {
        String stem = jsonFile.getFileName().toString();
        stem = stem.substring(0, stem.length() - ".json".length());
        Path outFile = outDir.resolve(stem + ".yaml");
        try {
          ObjectNode node = (ObjectNode) jackson.readTree(Files.newBufferedReader(jsonFile));
          TemplateSchemaArtifact template = reader.readTemplateSchemaArtifact(node);
          LinkedHashMap<String, Object> yamlMap = renderer.renderTemplateSchemaArtifact(template);
          // The library's YAML renderer puts raw java.net.URI / OffsetDateTime objects
          // into the map. SnakeYAML's default representer emits those with Java type
          // tags ("!!java.net.URI { }") that the strict reader can't ingest. Walk the
          // tree and replace those scalar holders with plain strings before dumping.
          stringifyJavaScalars(yamlMap);
          String yamlText = new Yaml(opts).dump(yamlMap);
          Files.writeString(outFile, yamlText, StandardCharsets.UTF_8);
          System.out.println("ok  " + stem);
          ok++;
        } catch (Exception e) {
          System.err.println("FAIL " + stem + " -- " + e.getClass().getSimpleName()
              + ": " + e.getMessage());
          fail++;
        }
      }
    }
    System.out.println();
    System.out.println("Generated " + ok + " golden YAML files; " + fail + " failures.");
    if (fail > 0) System.exit(2);
  }

  /**
   * Recursively walks a YAML-shaped Object tree (Map / List / scalar) and replaces
   * any non-YAML-native scalar with its {@code toString()} form. The library's YAML
   * renderer leaves several types as live Java objects ({@link URI}, {@link OffsetDateTime},
   * field-datatype enums like {@code XsdNumericDatatype}, etc.). SnakeYAML's default
   * representer emits those with Java type tags ({@code !!org.metadatacenter...}) that
   * the strict YAML reader cannot ingest.
   *
   * <p>"YAML-native scalar" here means: {@code null}, {@code String}, {@code Number},
   * {@code Boolean}, plus the recursable {@code Map} and {@code List} containers.
   * Everything else gets stringified.
   */
  @SuppressWarnings("unchecked")
  private static Object stringifyJavaScalars(Object node)
  {
    if (node == null) return null;
    if (node instanceof java.util.Map<?, ?>) {
      java.util.Map<String, Object> map = (java.util.Map<String, Object>) node;
      for (java.util.Map.Entry<String, Object> entry : map.entrySet())
        entry.setValue(stringifyJavaScalars(entry.getValue()));
      return map;
    }
    if (node instanceof java.util.List<?>) {
      java.util.List<Object> list = (java.util.List<Object>) node;
      for (int i = 0; i < list.size(); i++) list.set(i, stringifyJavaScalars(list.get(i)));
      return list;
    }
    if (node instanceof String || node instanceof Number || node instanceof Boolean)
      return node;
    return node.toString();
  }
}
