package org.metadatacenter.artifacts.mcp;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.modelcontextprotocol.spec.McpSchema;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.metadatacenter.artifacts.mcp.tools.TemplateFromYamlTool;
import org.metadatacenter.model.validation.CedarValidator;
import org.metadatacenter.model.validation.ModelValidator;
import org.metadatacenter.model.validation.report.ErrorItem;
import org.metadatacenter.model.validation.report.ValidationReport;

import java.net.URL;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Real-world battery: runs {@code template_from_yaml} against the golden YAML
 * fixtures derived from the
 * <a href="https://github.com/hubmapconsortium/dataset-metadata-spreadsheet">HuBMAP
 * template library</a> and confirms each compiles to a JSON Schema that
 * {@link CedarValidator} accepts.
 *
 * <p>The fixtures under {@code src/test/resources/hubmap-golden/} are not the
 * original HuBMAP YAML files. The originals were generated by an older toolchain
 * and contain deviations from current canonical CEDAR YAML (no {@code modelVersion},
 * bare-integer label values, etc.). The fixtures here are produced by
 * {@link GoldenYamlGenerator}, which round-trips the paired authoritative JSON
 * Schemas through the artifact library's own reader+renderer to recover what the
 * library considers the canonical YAML form. Re-generate by pointing the
 * generator at any directory of paired CEDAR JSON Schemas.
 *
 * <p>Failures are reported per template name so a regression in one of the 44
 * templates is identifiable without re-running the rest.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
final class HubmapTemplatesIT
{
  private static final String FIXTURES_RESOURCE = "hubmap-golden";

  private final ObjectMapper jackson = new ObjectMapper();
  private final ModelValidator cedarValidator = new CedarValidator();

  private final List<String> passes = new ArrayList<>();
  private final List<String> failures = new ArrayList<>();

  @BeforeAll void announceBattery()
  {
    System.out.println("[HubmapTemplatesIT] running against vendored golden YAML in "
        + "src/test/resources/" + FIXTURES_RESOURCE + "/");
  }

  @AfterAll void printSummary()
  {
    int total = passes.size() + failures.size();
    System.out.println("[HubmapTemplatesIT] summary: "
        + passes.size() + "/" + total + " templates compiled and validated");
    if (!failures.isEmpty()) {
      System.out.println("[HubmapTemplatesIT] failures:");
      for (String f : failures) System.out.println("  - " + f);
    }
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("templates")
  void compiles_and_validates_template_from_yaml(String displayName, Path yamlFile)
      throws Exception
  {
    String yamlText = Files.readString(yamlFile);

    McpSchema.CallToolResult result = invoke(yamlText);

    if (result.isError()) {
      String detail = ((McpSchema.TextContent) result.content().get(0)).text();
      failures.add(displayName + " — handler error: " + truncate(detail, 200));
      fail("template_from_yaml returned isError=true for " + yamlFile.getFileName() + ":\n  " + detail);
    }

    String json = ((McpSchema.TextContent) result.content().get(0)).text();
    JsonNode parsed;
    try {
      parsed = jackson.readTree(json);
    } catch (Exception e) {
      failures.add(displayName + " — output not parseable as JSON");
      throw e;
    }

    ValidationReport report = cedarValidator.validateTemplate(parsed);
    if (!"true".equals(report.getValidationStatus())) {
      StringBuilder msg = new StringBuilder(
          "CedarValidator rejected the compiled output for " + yamlFile.getFileName() + ":\n");
      for (ErrorItem err : report.getErrors()) msg.append("  - ").append(err).append('\n');
      failures.add(displayName + " — CedarValidator rejected compiled output");
      fail(msg.toString());
    }

    passes.add(displayName);
  }

  // ---------------------------------------------------------------------
  // argument source: every *.yaml in the vendored fixtures resource folder
  // ---------------------------------------------------------------------

  Stream<Arguments> templates() throws Exception
  {
    URL resource = getClass().getClassLoader().getResource(FIXTURES_RESOURCE);
    assertNotNull(resource,
        "fixtures folder not on classpath: src/test/resources/" + FIXTURES_RESOURCE);
    Path dir = Paths.get(resource.toURI());

    List<Arguments> args = new ArrayList<>();
    try (DirectoryStream<Path> ds = Files.newDirectoryStream(dir, "*.yaml")) {
      for (Path yaml : ds) {
        String stem = yaml.getFileName().toString();
        String displayName = stem.substring(0, stem.length() - ".yaml".length());
        args.add(Arguments.of(displayName, yaml));
      }
    }
    args.sort((a, b) -> ((String) a.get()[0]).compareTo((String) b.get()[0]));
    return args.stream();
  }

  // ---------------------------------------------------------------------
  // helpers
  // ---------------------------------------------------------------------

  private static McpSchema.CallToolResult invoke(String yaml)
  {
    return TemplateFromYamlTool.handler(null,
        new McpSchema.CallToolRequest("template_from_yaml", Map.of("yaml", yaml)));
  }

  private static String truncate(String s, int limit)
  {
    return s.length() <= limit ? s : s.substring(0, limit) + "...";
  }
}
